// src/app/insights/page.tsx
'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';

interface Stats {
  total: number; blocked: number; stepUps: number;
  success: number; blockRate: number; avgScopeReduction: number;
}

const IconArrowLeft = () => (
  <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
    <line x1="19" y1="12" x2="5" y2="12"/><polyline points="12 19 5 12 12 5"/>
  </svg>
);

const GRAVITEE_STATS = [
  { stat: '88%', label: 'of organizations reported AI agent security incidents in 2026', source: 'Gravitee State of AI Agent Security 2026 (n=919)' },
  { stat: '78%', label: 'cannot trace agent actions back to a specific agent identity', source: 'Gravitee — Identity Is The Weakest Link' },
  { stat: '45.6%', label: 'still use shared API keys for agent-to-agent authentication', source: 'Gravitee — Agent-to-Agent Authentication Methods' },
  { stat: '57.4%', label: 'cite insufficient logging and audit trails as primary concern', source: 'Gravitee — Main Security Concerns When Building Agents' },
  { stat: '27.2%', label: 'use custom hardcoded authorization logic — difficult to audit at scale', source: 'Gravitee — Authorization Is Often Hardcoded' },
  { stat: '14.4%', label: 'only have full IT/security approval for their entire agent fleet', source: 'Gravitee — Shadow AI section' },
];

const SCOPEGUARD_INSIGHTS = [
  {
    title: 'LLM alone cannot secure authorization',
    body: 'When Layer 3 (Gemini) analyzed search_flights, it correctly returned 0 scopes — but this only happened because Layer 2 had already confirmed the action was within hard constraints. Without L2, a prompt injection could convince the LLM to classify a malicious action as low-risk.',
    finding: 'Hard constraints must run before LLM — not after.',
    color: '#ef4444',
  },
  {
    title: 'Agents routinely request more than they need',
    body: 'The travel agent declared 3 capabilities (payment:write, calendar:events:write, email:send). For a simple flight search, Gemini determined 0 scopes were needed. For booking, only 2 of 3 were needed. This means the declared scope set was 33–100% over-permissive for actual actions.',
    finding: 'Dynamic scope minimization reduces blast radius by 33–100% per action.',
    color: '#2563eb',
  },
  {
    title: 'Identity is the prerequisite for all other security controls',
    body: 'Without a unique agent_id claim in the token, the gateway cannot enforce per-agent limits, cannot produce meaningful audit logs, and cannot support revocation. Every other security property depends on identity being resolved first.',
    finding: 'Agent identity (Auth0 M2M) is the load-bearing layer — without it, none of the other controls are attributable.',
    color: '#8b5cf6',
  },
  {
    title: 'Step-up auth needs to be scoped to the specific action',
    body: 'Generic "please approve" notifications have 0 context for the user. CIBA binding_message with natural language explanation (generated by Gemini) gives users enough information to make an informed decision — which is the entire point of user consent.',
    finding: 'Consent is only meaningful if the user understands what they are consenting to.',
    color: '#f59e0b',
  },
];

export default function InsightsPage() {
  const [stats, setStats] = useState<Stats | null>(null);

  useEffect(() => {
    fetch('/api/audit').then(r => r.json()).then(d => setStats(d.stats));
  }, []);

  return (
    <>
      <style>{`
        @import url('https://fonts.googleapis.com/css2?family=DM+Sans:wght@300;400;500;600&family=JetBrains+Mono:wght@400;500&display=swap');
        *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
        body { background: var(--bg); font-family: var(--font); color: var(--text); }
        .page { max-width: 860px; margin: 0 auto; padding: 40px 24px 80px; }
        .back-link { display: inline-flex; align-items: center; gap: 6px; color: var(--text-3); font-size: 13px; text-decoration: none; margin-bottom: 28px; }
        .back-link:hover { color: var(--text-2); }
        .page-title { font-size: 24px; font-weight: 600; letter-spacing: -0.5px; margin-bottom: 6px; }
        .page-sub { font-size: 14px; color: var(--text-2); line-height: 1.6; margin-bottom: 32px; }
        .section-title { font-size: 12px; font-weight: 600; color: var(--text-3); text-transform: uppercase; letter-spacing: 0.7px; margin-bottom: 14px; }
        .stats-row { display: grid; grid-template-columns: repeat(3, 1fr); gap: 12px; margin-bottom: 32px; }
        .stat-card { background: var(--surface); border: 0.5px solid var(--border); border-radius: 12px; padding: 16px; }
        .stat-num { font-size: 28px; font-weight: 700; font-family: var(--mono); }
        .stat-label { font-size: 12px; color: var(--text-2); margin-top: 4px; }
        .gravitee-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 10px; margin-bottom: 32px; }
        .gravitee-card { background: var(--surface); border: 0.5px solid var(--border); border-radius: 12px; padding: 16px; }
        .g-stat { font-size: 22px; font-weight: 700; font-family: var(--mono); color: #f97316; margin-bottom: 6px; }
        .g-label { font-size: 13px; color: var(--text-2); line-height: 1.5; margin-bottom: 8px; }
        .g-source { font-size: 11px; color: var(--text-3); font-style: italic; }
        .insight-list { display: flex; flex-direction: column; gap: 14px; margin-bottom: 32px; }
        .insight-card { background: var(--surface); border: 0.5px solid var(--border); border-radius: 14px; padding: 20px; border-left: 3px solid transparent; }
        .insight-title { font-size: 15px; font-weight: 600; margin-bottom: 10px; }
        .insight-body { font-size: 13px; color: var(--text-2); line-height: 1.65; margin-bottom: 12px; }
        .insight-finding { font-size: 13px; font-weight: 500; padding: 10px 14px; border-radius: 8px; }
      `}</style>
      <div className="page">
        <Link href="/dashboard" className="back-link">
          <IconArrowLeft /> Back to Dashboard
        </Link>

        <h1 className="page-title">Security Insights</h1>
        <p className="page-sub">
          Patterns and findings surfaced by ScopeGuard — grounded in data from the
          Gravitee State of AI Agent Security 2026 report (919 practitioners surveyed)
          and live observations from the demo agent.
        </p>

        {/* Live stats */}
        {stats && (
          <>
            <div className="section-title">Live metrics from this session</div>
            <div className="stats-row">
              <div className="stat-card">
                <div className="stat-num" style={{ color: '#10b981' }}>{stats.avgScopeReduction}%</div>
                <div className="stat-label">Average scope reduction — agents received fewer permissions than declared</div>
              </div>
              <div className="stat-card">
                <div className="stat-num" style={{ color: '#ef4444' }}>{stats.blockRate}%</div>
                <div className="stat-label">Of requests blocked by hard constraints before reaching LLM</div>
              </div>
              <div className="stat-card">
                <div className="stat-num" style={{ color: '#f59e0b' }}>{stats.stepUps}</div>
                <div className="stat-label">High-stakes actions that required explicit user approval</div>
              </div>
            </div>
          </>
        )}

        {/* Gravitee data */}
        <div className="section-title">Industry context — why this matters</div>
        <div className="gravitee-grid">
          {GRAVITEE_STATS.map(({ stat, label, source }) => (
            <div key={stat} className="gravitee-card">
              <div className="g-stat">{stat}</div>
              <div className="g-label">{label}</div>
              <div className="g-source">{source}</div>
            </div>
          ))}
        </div>

        {/* ScopeGuard insights */}
        <div className="section-title">Findings from building ScopeGuard</div>
        <div className="insight-list">
          {SCOPEGUARD_INSIGHTS.map(({ title, body, finding, color }) => (
            <div key={title} className="insight-card" style={{ borderLeftColor: color }}>
              <div className="insight-title">{title}</div>
              <div className="insight-body">{body}</div>
              <div className="insight-finding" style={{ background: `${color}15`, color }}>
                Finding: {finding}
              </div>
            </div>
          ))}
        </div>
      </div>
    </>
  );
}